services:
  nginx:
    image: nginx:latest
    ports: [80:80, 443:443]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
  identity_service:
    build: ./identity
    ports: [5000:5000]
    volumes:
      - ./identity/config.yml:/app/config.yml:ro
      - ./identity/keys:/app/keys:ro
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports: [6379:6379]
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=secret
  sms-service-stub:
    build:
      context: sms-service-stub
      dockerfile: Dockerfile
  user-service-stub:
    build:
      context: user-service-stub
      dockerfile: Dockerfile
volumes:
  redis_data: